# Generated by Django 5.2.5 on 2025-08-19 14:40

import django.core.validators
import ecommerce.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5), ecommerce.validation.validate_half_or_whole]),
        ),
    ]
